"""fix relation between custom value and custom field

Revision ID: 01be48f3be8f
Revises: eb8586ada131
Create Date: 2024-12-26 13:17:11.943479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01be48f3be8f'
down_revision: Union[str, None] = 'eb8586ada131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custom_value_custom_field_id_key', 'custom_value', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('custom_value_custom_field_id_key', 'custom_value', ['custom_field_id'])
    # ### end Alembic commands ###
