"""cascade all between team and user team

Revision ID: 3376f4bb4145
Revises: 01be48f3be8f
Create Date: 2024-12-30 14:20:55.893942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3376f4bb4145'
down_revision: Union[str, None] = '01be48f3be8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_team_team_id_fkey', 'user_team', type_='foreignkey')
    op.create_foreign_key(None, 'user_team', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_team', type_='foreignkey')
    op.create_foreign_key('user_team_team_id_fkey', 'user_team', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
