"""not unique user_id in booking

Revision ID: 4f07c1897662
Revises: 6972c8e7ad49
Create Date: 2024-11-08 00:02:25.694258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f07c1897662'
down_revision: Union[str, None] = '6972c8e7ad49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_user_id_key', 'booking', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('booking_user_id_key', 'booking', ['user_id'])
    # ### end Alembic commands ###
