"""remove theme from event

Revision ID: 5087114dcb18
Revises: f49dcfea226d
Create Date: 2024-11-11 19:52:41.552604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5087114dcb18'
down_revision: Union[str, None] = 'f49dcfea226d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('theme', postgresql.ENUM('learning', 'management', name='themeenum'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
