"""registration_link in Event

Revision ID: 52519956179e
Revises: 90cb06ac723c
Create Date: 2024-10-27 16:26:37.183443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52519956179e'
down_revision: Union[str, None] = '90cb06ac723c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('registration_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'registration_link')
    # ### end Alembic commands ###
