"""custom value & custom field relationship

Revision ID: 6972c8e7ad49
Revises: 3c01ad52a0dd
Create Date: 2024-11-06 20:15:33.585912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6972c8e7ad49'
down_revision: Union[str, None] = '3c01ad52a0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('event_time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'event_time', ['event_time_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'event_time_id')
    # ### end Alembic commands ###
