"""description in event time

Revision ID: 7529695f9c83
Revises: c1546c995298
Create Date: 2024-11-19 22:43:14.676098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7529695f9c83'
down_revision: Union[str, None] = 'c1546c995298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_time', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_time', 'description')
    # ### end Alembic commands ###
