"""registration_link in team

Revision ID: 7c1a6b9ae81a
Revises: 962ab4ab50ef
Create Date: 2024-12-03 17:31:26.897439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1a6b9ae81a'
down_revision: Union[str, None] = '962ab4ab50ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('registration_link', sa.String(), nullable=True))
    op.add_column('user_team', sa.Column('registration_link', sa.String(), nullable=True))
    op.alter_column('user_team', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_team', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_team', 'registration_link')
    op.drop_column('team', 'registration_link')
    # ### end Alembic commands ###
