"""online link for event

Revision ID: 9470cbd18d71
Revises: 9ff1836881c1
Create Date: 2024-12-17 19:59:54.956369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9470cbd18d71'
down_revision: Union[str, None] = '9ff1836881c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('online_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'online_link')
    # ### end Alembic commands ###
