"""update FormatEnum

Revision ID: 9ecba3d9c8ad
Revises: 7c1a6b9ae81a
Create Date: 2024-12-05 01:00:50.441970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ecba3d9c8ad'
down_revision: Union[str, None] = '7c1a6b9ae81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
