"""schedule in Event

Revision ID: 9ff1836881c1
Revises: f2b78d49d433
Create Date: 2024-12-08 16:22:46.117329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff1836881c1'
down_revision: Union[str, None] = 'f2b78d49d433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('schedule', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'schedule')
    # ### end Alembic commands ###
