"""format

Revision ID: ba1113ff04f2
Revises: 9ecba3d9c8ad
Create Date: 2024-12-05 01:32:29.901040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba1113ff04f2'
down_revision: Union[str, None] = '9ecba3d9c8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'format',
               existing_type=postgresql.ENUM('lecture', 'seminar', 'workshop', 'master_class', 'competition', 'meeting', 'conference', 'panel_discussion', 'round_table', 'pitch', 'hackathon', 'online', name='formatenum'),
               type_=sa.Enum('accelerator', 'workshop', 'meeting', 'exhibition', 'open_day', 'conference', 'round_table', 'lecture', 'master_class', 'methoda', 'meetup', 'panel_discussion', 'pitch', 'seminar', 'competition', 'gathering', 'strategic_session', 'foresight', 'forum', 'hackathon', name='formatenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'format',
               existing_type=sa.Enum('accelerator', 'workshop', 'meeting', 'exhibition', 'open_day', 'conference', 'round_table', 'lecture', 'master_class', 'methoda', 'meetup', 'panel_discussion', 'pitch', 'seminar', 'competition', 'gathering', 'strategic_session', 'foresight', 'forum', 'hackathon', name='formatenum', native_enum=False),
               type_=postgresql.ENUM('lecture', 'seminar', 'workshop', 'master_class', 'competition', 'meeting', 'conference', 'panel_discussion', 'round_table', 'pitch', 'hackathon', 'online', name='formatenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
