"""event model & linked

Revision ID: c90c133fc1f4
Revises: d341da2510b4
Create Date: 2024-10-22 16:38:35.283369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90c133fc1f4'
down_revision: Union[str, None] = 'd341da2510b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('theme', sa.Enum('learning', 'management', name='themeenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('visit_cost', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'close', name='statusenum'), nullable=False),
    sa.Column('format', sa.Enum('lecture', 'seminar', 'workshop', 'master_class', 'competition', 'meeting', 'conference', 'panel_discussion', 'round_table', 'pitch', 'hackathon', 'online', name='formatenum'), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('seats_number', sa.Integer(), nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['event_date.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['event_id'])
    op.create_foreign_key(None, 'user', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'event_id')
    op.drop_table('event_time')
    op.drop_table('file')
    op.drop_table('event_date')
    op.drop_table('custom_field')
    op.drop_table('event')
    # ### end Alembic commands ###
