"""user additional fields

Revision ID: d341da2510b4
Revises: a61761e1d33c
Create Date: 2024-10-15 19:46:19.306942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd341da2510b4'
down_revision: Union[str, None] = 'a61761e1d33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('vk', sa.String(), nullable=True))
    op.add_column('user', sa.Column('telegram', sa.String(), nullable=True))
    op.add_column('user', sa.Column('whatsapp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'whatsapp')
    op.drop_column('user', 'telegram')
    op.drop_column('user', 'vk')
    op.drop_column('user', 'company_name')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
