"""cascade parameters for event models

Revision ID: e0df2d41872d
Revises: 9470cbd18d71
Create Date: 2024-12-17 21:41:52.196767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0df2d41872d'
down_revision: Union[str, None] = '9470cbd18d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_event_date_time_id_fkey', 'booking', type_='foreignkey')
    op.create_foreign_key(None, 'booking', 'event_date_time', ['event_date_time_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_foreign_key('booking_event_date_time_id_fkey', 'booking', 'event_date_time', ['event_date_time_id'], ['id'])
    # ### end Alembic commands ###
