"""switch from age to birth_date in User model

Revision ID: f49dcfea226d
Revises: 4f07c1897662
Create Date: 2024-11-11 19:45:14.565763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49dcfea226d'
down_revision: Union[str, None] = '4f07c1897662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
